### ISSUE TITLE
FeedPoster example error 

### ISSUE THREAD

**Issue by dhrjklt** [fbsamples/workplace-platform-samples#31]
/root/workplace-platform-samples/FeedPoster/node_modules/cron/lib/cron.js:295
		source = this.source.replace(/[a-z]{1,3}/ig, function(alias) {
		                                     ^

TypeError: Cannot read property 'replace' of undefined
    at Object._parse (/root/workplace-platform-samples/FeedPoster/node_modules/cron/lib/cron.js:295:23)
    at Object.CronTime (/root/workplace-platform-samples/FeedPoster/node_modules/cron/lib/cron.js:37:8)
    at new CronJob (/root/workplace-platform-samples/FeedPoster/node_modules/cron/lib/cron.js:395:18)
    at Object.<anonymous> (/root/workplace-platform-samples/FeedPoster/clock.js:65:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

Please help me out, I am a beginner in node

**Comment by connortreacy** [comment]
This looks like it might be an issue with the cron format you're using in your `.env` file. Double-check the info in that file and try again, and feel free to open another issue if you have more issues.
